name: unofficial_paypal_sdk
description: Unofficial pay pal SDK
version: 0.0.2+3
repository: https://github.com/LiveUser/paypal

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  sexy_api_client: ^0.0.6+6
  
dev_dependencies:
  test: ^1.16.0
  power_plant: ^1.0.2+3